### ISSUE TITLE
Listening to media events

### ISSUE THREAD

**Issue by danielr18** [benwiley4000/cassette#304]
I think the documentation is outdated with regards to this:

> onMediaEvent: An object where the keys are media event types and the values are callback functions. undefined by default.
> 
> mediaElementRef: A callback function called after the component mounts and before it unmounts. Similar to React ref callback prop but its only parameter is the internally-referenced HTML media element, not the component itself. undefined by default. NOTE: This ref should not be used for media element event listeners; use onMediaEvent.

It seems like `onMediaEvent` has been removed, does that mean we should use media ref to listen to events?

**Comment by benwiley4000** [comment]
@danielr18 yes, that was the idea. Basically, I want to encourage folks to consume media state as props inside the PlayerContextProvider rather than listen to events from outside. It's still possible to use mediaElementRef if desired, as you said.

By the way, the README documentation is super out-of-date and is meant to be replaced by these docs: https://benwiley4000.github.io/cassette/styleguide/ however they still need a lot of work before they're finished. For example all the prop types to the PlayerContextProvider are listed but no prop descriptions at the moment.

**Comment by danielr18** [comment]
It would be nice to be able to have a callback for certain events, e.g. forwardSkip, backwardSkip.

One of the use cases I have is that you can only `forwardSkip`, playlist being kind of a queue, there's a "playing now" track (playlist[0]) and the rest of the playlist are the next in the queue, so I would need to update the playlist when the track changes.

I can see that PlayerContextProvider's `getDerivedStateFromProps` can support this without interrupting reproduction, as if I change the playlist and move one of the tracks in it to another index, the provider state will be updated with the new `activeTrackIndex`.

I was thinking in listening media's onended event for example, but it doesn't cover all cases, like doing forwardSkip with a MediaSession action.

Do you think it would be a good idea to be able to pass some props to `PlayerContextProvider` like `onForwardSkip` that get called after these actions execute? Or do you know if my use case is possible with the current spec? Any thoughts are really appreciated

**Comment by benwiley4000** [comment]
Thanks for explaining your use case. It seems like you're creating a sort of Pandora-style radio queue?

Here is the issue for which I removed `onActiveTrackUpdate` which would have solved your use case: https://github.com/benwiley4000/cassette/issues/196 😄 The assumption I made was that these callbacks would only be desired for updating UI derived from the media state, but I hadn't considered the use case of transforming the props that get passed in like `playlist`.

However I'm wondering.. is it totally necessary that you remove the tracks from the front of the playlist after they're done? Could you just keep them in the playlist? If the concern is that a user could go back to these tracks should they ever reach the end of the playlist, you could use the `defaultRepeatStrategy` prop (which is not yet well-documented, sorry) and set it to `'none'`.

**Comment by danielr18** [comment]
I think you are right, I can probably get away without having to transform the playlist. I could connect  both my playlist context and cassette's player one in the component that displays the queue, showing only `playlist.slice(activeTrackIndex)`. I'll see how far can I get with that.

Anyways, I'm happy to work on a PR if needed 👍

**Comment by benwiley4000** [comment]
@danielr18 yeah I had a similar thought. Let me know how that goes. If it doesn't work well please let me know! I want things to feel ergonomic. :)

**Comment by benwiley4000** [comment]
And I could potentially see an argument for bringing back `onActiveTrackUpdate`. Unlike the rest of the callbacks that got removed, it concerns a prop (`playlist`) that can change. It doesn't sit totally well with me that you could have a memory leak just because you don't have a good hook for doing cleanup, so if you want to make a PR to bring that back (consulting this PR https://github.com/benwiley4000/cassette/issues/196), I would be ok with that. 🙂

**Comment by benwiley4000** [comment]
The new `onActiveTrackUpdate` is added in v2.0.0-alpha.8! :) https://github.com/benwiley4000/cassette/releases/tag/v2.0.0-alpha.8
